### ISSUE TITLE
What is the rationale behind omission of "Requires-Dist" in sdist PKG_INFO?

### ISSUE THREAD

**Issue by lelit** [pdm-project/pdm-pep517#110]
I noticed that the sdist `PKG_INFO` file does not contain any of the dependencies of the package, neither the mandatory ones nor the optional ones, although it carries the `Provides-Extra` field.
Is there any reason [this difference](https://github.com/pdm-project/pdm-pep517/blob/master/pdm/pep517/base.py#L412) between sdist and wheel?

**Comment by frostming** [comment]
An sdist doesn't contain any static information about requirements, since they will vary depending on the platform the build is performed on. Say, it is allowed for an sdist to have different requirements on Linux and Windows. On the contrary, wheel is a static distribution format, which contains all information and files necessary, the installer only needs to extract it to the destination.

**Comment by lelit** [comment]
So, maybe the `Provides-Extra` is pointless?

**Comment by frostming** [comment]
Yeah I think so
