### ISSUE TITLE
Different names generated for sdist and wheel

### ISSUE THREAD

**Issue by lelit** [pdm-project/pdm-pep517#111]
Sorry to bother you, but I'm getting crazy trying to understand _modern_ packaging rules, and here I'm asking an opinion/confirmation.

I'm trying to _modernize_ this aspect of several projects of mine, replacing `setup.py` with `pyproject.toml`, and I had different issues with every _build system_ I tried, maybe due to the peculiar name scheme I followed for them, or instead because the specifications are imprecise and everyone interprets them in different ways.

I found your project the less problematic as of now (read, I did **not** have _any_ issue), and I'm taking the opportunity to say "thank you!".

Today I converted another project, whose distribution name is `metapensiero.sphinx.autodoc_sa`: everything went smooth, except that I noticed a difference in the name of the generated file for sdist and wheel:
```
$ ls -rt1 dist/
...
metapensiero.sphinx.autodoc_sa-1.7.tar.gz
metapensiero.sphinx.autodoc_sa-2.0.tar.gz
metapensiero.sphinx.autodoc_sa-2.1.tar.gz
metapensiero.sphinx.autodoc-sa-2.2.dev0.tar.gz
metapensiero.sphinx.autodoc_sa-2.2.dev0-py3-none-any.whl
```

The latest version, 2.2.dev0, is the one converted to use `pdm-pep517`: as you can see, the sdist contains `autodoc-sa` (with an hypen) while the wheel has `autodoc_sa` (with underscore). Previous versions were generated by `setuptools` (that is, by `python setup.py sdist`).

I tried uploading those new archives to [test.pypi.org](https://test.pypi.org/project/metapensiero.sphinx.autodoc-sa/) and they were accepted: at first I expected a rejection due to different name, as it happened for one other project when I used `flit` as build system, but I was wrong :-)

To satisfy my curiosity, I tried to find references to the file name conventions, and I found [this section on PyPA](https://packaging.python.org/en/latest/specifications/source-distribution-format/#source-distribution-file-name):

> The file name of a sdist is not currently standardised, although the de facto form is {name}-{version}.tar.gz, where {name} is the canonicalized form of the project name (see [PEP 503](https://www.python.org/dev/peps/pep-0503) for the canonicalization rules) with - characters replaced with _

That makes me wonder: it seems rather contradictory that it first [suggests](https://peps.python.org/pep-0503/#normalized-names) to replace runs of _invalid_ characters with a single hyphen, but then says to replace that hyphen with an underscore.

So the question is: should I relax and accept the apparent confusion, or is there an issue in the way `pdm-pep517` generates the sdist (using [metadata.project_name](https://github.com/pdm-project/pdm-pep517/blob/master/pdm/pep517/sdist.py#L66)) vs the wheel (that instead uses [metadata.project_filename](https://github.com/pdm-project/pdm-pep517/blob/master/pdm/pep517/wheel.py#L89))?

Thanks again!

**Comment by frostming** [comment]
I think sdist just has no opinion on this, while wheel will [convert the hyphens to underscores](https://github.com/frostming/pdm-pep517/blob/814442bc13451e8e43ddb7ac47fdda0764624d3b/pdm/pep517/utils.py#L45), because hyphens are used to separate parts in the filename. I just borrow this part from setuptools and they should have the same behavior. See [Flask-SQLAlchemy](https://pypi.org/project/Flask-SQLAlchemy/#files) for example, note the name normalization.

AFAIK, different build backends treat this differently. `hatchling` lowercases the distribution name and replaces `.` to `_` as well, but `setuptools` and `pdm-pep517` keep the dots

Some useful links

- Wheel format: https://peps.python.org/pep-0427/#escaping-and-unicode
- https://discuss.python.org/t/amending-pep-427-and-pep-625-on-package-normalization-rules/

**Comment by lelit** [comment]
Thank you. It's just a matter of handling the difference in my `twine`-based upload rule.
